### ISSUE TITLE
`get_demand` function in `FoodPantry` class

### ISSUE THREAD

**Issue by rodigu** [Liu-Hy/Food-Bank-Network-Simulation#4]
Can @Liu-Hy add a `get_demant` function that returns the demand for each of the products pls

It can return a `dict` with keys being the types and values being the demand in weight.
I need the real demand, regardless if ir was met or not. This is to calculate how much of each food the bank will need to buy.

**Comment by rodigu** [comment]
I think historical, cumulative demand would be more useful than weekly demand, what do you think @Liu-Hy

**Comment by Liu-Hy** [comment]
Because daily donation fluctuates greatly, a running average (or exponential smoothing) of previous data should be better than single week data. In my design, client demand is not observable. The pantry owner can only estimate demand based on the amount of food consumed at previous pantries, and the number of clients before the food runs out. I plan to record it in FoodPantry.previous_record, and you will be able to access that. 
IMO, comparing the daily donated food and the food sent to pantries in the past few days is enough for foodbanks to make decisions, and it seems more realistic not to know the exact demand of clients. This is challenging, so I've been thinking about how to make this easier when designing the Foodbank methods. Using Food.subtract() together with Food.quality_control(), every day food banks may plan several days ahead to answer question such as: how much food would be wasted should we not share them to other food banks? How much food do we lack to maintain our inventory in the next 3 days? (To do so, we may remove the input check in .subtract() to allow negative quantities). 
The exact demand data is in the subcolumns named "total" in the dataframe FoodPantry.clients. It is easy to write the function, but I have a deadline on 30th morning. Let's talk on Wednesday.

**Comment by rodigu** [comment]
I will use the orders to estimate demand for #1

**Comment by Liu-Hy** [comment]
Correction: the Food.subtract() does not allow subtracting more than it has, and it cannot be modified to do so. When estimating the lack of food, try using it combined with .get_quantity(), or write your own. @rodigu
